### ISSUE TITLE
buttons for movie titles get truncated

### ISSUE THREAD

**Issue by lchamber-luc** [ryanmark1867/chatbot#37]
buttons titles get truncated to about 20 characters.  may make it hard to identify the movie.   is there a way to widen the button?  

Test on iPhone 7 and iPad

**Comment by ryanmark1867** [comment]
@lchamber-luc - Facebook documents a 20 character limit for text in quick replies (the kinds of buttons we're using to display the movie names in step 3 of demo 1) - 

"The text to display on the quick reply button. 20 character limit." in https://developers.facebook.com/docs/messenger-platform/reference/send-api/quick-replies/

I searched extensively and I don't see any way around this limit on the maximum text length for quick reply button text.

An alternative (has some risk for demo 1 at this stage) is to use a carousel rather than quick replies in step 3. The carousel could have the movie poster, movie title, and a button that when clicked would perform the same action as the quick replies in step 3 currently. Carousel title can be 80 characters long, so this would address the truncated movie title problem. 

PROS:
- allows full  movie title to be shown in step 3 of demo

CONS:
- non-trivial, net new coding effort. I estimate 3-4 hours to implement & test
- performance will be worse for showing the carousel in step 3 than it is for quick replies in step 3
- kind of heavy weight treatment for this stage of the demo, and IMO makes too much of the overall demo interaction dependent on carousel (would be steps 3, 5, and 7

I'll wait for us to discuss pros and cons before I make any code changes related to this.

**Comment by ryanmark1867** [comment]
Fixed by using carousel to show the examples of sci-fi movies in step 3:

![image](https://user-images.githubusercontent.com/39224115/76177190-cb73d000-6189-11ea-934e-0378e5c2c631.png)
